name: Deploy to Development or Production

on:
  push:
    branches:
      - main    # Production branch

jobs:
  # Production deployment job
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # This job will only run for the 'main' branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .ssh directory and add Production Server to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.PROD_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Install SSH Key for Production
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

      - name: Deploy to Production Server
        run: |
          ssh root@${{ secrets.PROD_SERVER_IP }} "
            cd /var/www/manavault_backend_prod/manavault_backend &&
            git fetch origin main &&
            git reset --hard origin/main &&
            npm install &&
            npm run build &&
            pm2 start ecosystem.config.js --env production
          "
